# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoverOptionsPage(object):
    def setupUi(self, CoverOptionsPage):
        CoverOptionsPage.setObjectName("CoverOptionsPage")
        CoverOptionsPage.resize(559, 651)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoverOptionsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.save_images_to_tags = QtWidgets.QGroupBox(CoverOptionsPage)
        self.save_images_to_tags.setCheckable(True)
        self.save_images_to_tags.setChecked(False)
        self.save_images_to_tags.setObjectName("save_images_to_tags")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.save_images_to_tags)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setObjectName("vboxlayout")
        self.cb_embed_front_only = QtWidgets.QCheckBox(self.save_images_to_tags)
        self.cb_embed_front_only.setObjectName("cb_embed_front_only")
        self.vboxlayout.addWidget(self.cb_embed_front_only)
        self.verticalLayout.addWidget(self.save_images_to_tags)
        self.save_images_to_files = QtWidgets.QGroupBox(CoverOptionsPage)
        self.save_images_to_files.setCheckable(True)
        self.save_images_to_files.setChecked(False)
        self.save_images_to_files.setObjectName("save_images_to_files")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.save_images_to_files)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_use_filename = QtWidgets.QLabel(self.save_images_to_files)
        self.label_use_filename.setObjectName("label_use_filename")
        self.verticalLayout_2.addWidget(self.label_use_filename)
        self.cover_image_filename = QtWidgets.QLineEdit(self.save_images_to_files)
        self.cover_image_filename.setObjectName("cover_image_filename")
        self.verticalLayout_2.addWidget(self.cover_image_filename)
        self.save_images_overwrite = QtWidgets.QCheckBox(self.save_images_to_files)
        self.save_images_overwrite.setObjectName("save_images_overwrite")
        self.verticalLayout_2.addWidget(self.save_images_overwrite)
        self.save_only_one_front_image = QtWidgets.QCheckBox(self.save_images_to_files)
        self.save_only_one_front_image.setObjectName("save_only_one_front_image")
        self.verticalLayout_2.addWidget(self.save_only_one_front_image)
        self.image_type_as_filename = QtWidgets.QCheckBox(self.save_images_to_files)
        self.image_type_as_filename.setObjectName("image_type_as_filename")
        self.verticalLayout_2.addWidget(self.image_type_as_filename)
        self.verticalLayout.addWidget(self.save_images_to_files)
        self.ca_providers_groupbox = QtWidgets.QGroupBox(CoverOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ca_providers_groupbox.sizePolicy().hasHeightForWidth())
        self.ca_providers_groupbox.setSizePolicy(sizePolicy)
        self.ca_providers_groupbox.setObjectName("ca_providers_groupbox")
        self.ca_providers_layout = QtWidgets.QVBoxLayout(self.ca_providers_groupbox)
        self.ca_providers_layout.setObjectName("ca_providers_layout")
        self.ca_providers_list = QtWidgets.QListWidget(self.ca_providers_groupbox)
        self.ca_providers_list.setObjectName("ca_providers_list")
        self.ca_providers_layout.addWidget(self.ca_providers_list)
        self.ca_layout = QtWidgets.QHBoxLayout()
        self.ca_layout.setObjectName("ca_layout")
        self.move_label = QtWidgets.QLabel(self.ca_providers_groupbox)
        self.move_label.setObjectName("move_label")
        self.ca_layout.addWidget(self.move_label)
        self.up_button = QtWidgets.QToolButton(self.ca_providers_groupbox)
        self.up_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.up_button.setText("")
        icon = QtGui.QIcon.fromTheme(":/images/16x16/go-up.png")
        self.up_button.setIcon(icon)
        self.up_button.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.up_button.setAutoRaise(False)
        self.up_button.setObjectName("up_button")
        self.ca_layout.addWidget(self.up_button)
        self.down_button = QtWidgets.QToolButton(self.ca_providers_groupbox)
        self.down_button.setText("")
        icon = QtGui.QIcon.fromTheme(":/images/16x16/go-down.png")
        self.down_button.setIcon(icon)
        self.down_button.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.down_button.setObjectName("down_button")
        self.ca_layout.addWidget(self.down_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ca_layout.addItem(spacerItem)
        self.ca_providers_layout.addLayout(self.ca_layout)
        self.verticalLayout.addWidget(self.ca_providers_groupbox, 0, QtCore.Qt.AlignTop)
        self.load_local_cover_art = QtWidgets.QGroupBox(CoverOptionsPage)
        self.load_local_cover_art.setObjectName("load_local_cover_art")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.load_local_cover_art)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.local_cover_regex_label = QtWidgets.QLabel(self.load_local_cover_art)
        self.local_cover_regex_label.setObjectName("local_cover_regex_label")
        self.verticalLayout_3.addWidget(self.local_cover_regex_label)
        self.local_cover_regex_edit = QtWidgets.QLineEdit(self.load_local_cover_art)
        self.local_cover_regex_edit.setObjectName("local_cover_regex_edit")
        self.verticalLayout_3.addWidget(self.local_cover_regex_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.local_cover_regex_error = QtWidgets.QLabel(self.load_local_cover_art)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_cover_regex_error.sizePolicy().hasHeightForWidth())
        self.local_cover_regex_error.setSizePolicy(sizePolicy)
        self.local_cover_regex_error.setText("")
        self.local_cover_regex_error.setObjectName("local_cover_regex_error")
        self.horizontalLayout.addWidget(self.local_cover_regex_error)
        self.local_cover_regex_default = QtWidgets.QPushButton(self.load_local_cover_art)
        self.local_cover_regex_default.setObjectName("local_cover_regex_default")
        self.horizontalLayout.addWidget(self.local_cover_regex_default)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.local_cover_note = QtWidgets.QLabel(self.load_local_cover_art)
        font = QtGui.QFont()
        font.setItalic(True)
        self.local_cover_note.setFont(font)
        self.local_cover_note.setWordWrap(True)
        self.local_cover_note.setObjectName("local_cover_note")
        self.verticalLayout_3.addWidget(self.local_cover_note)
        self.verticalLayout.addWidget(self.load_local_cover_art)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(CoverOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(CoverOptionsPage)

    def retranslateUi(self, CoverOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.save_images_to_tags.setTitle(_("Embed cover images into tags"))
        self.cb_embed_front_only.setText(_("Embed only a single front image"))
        self.save_images_to_files.setTitle(_("Save cover images as separate files"))
        self.label_use_filename.setText(_("Use the following file name for images:"))
        self.save_images_overwrite.setText(_("Overwrite the file if it already exists"))
        self.save_only_one_front_image.setText(_("Save only a single front image as separate file"))
        self.image_type_as_filename.setText(_("Always use the primary image type as the file name for non-front images"))
        self.ca_providers_groupbox.setTitle(_("Cover Art Providers"))
        self.move_label.setText(_("Reorder Priority: "))
        self.up_button.setToolTip(_("Move selected item up"))
        self.down_button.setToolTip(_("Move selected item down"))
        self.load_local_cover_art.setTitle(_("Load cover art from local files"))
        self.local_cover_regex_label.setText(_("Local cover art files match the following regular expression:"))
        self.local_cover_regex_default.setText(_("Default"))
        self.local_cover_note.setText(_("First group in the regular expression, if any, will be used as type, ie. cover-back-spine.jpg will be set as types Back + Spine. If no type is found, it will default to Front type."))
