name: Test pip install

on: [push, pull_request]

jobs:
  pip-install: # Test whether a clean pip install from source works
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install gettext (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install gettext
    - name: Install gettext (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install gettext
        brew link gettext --force
        echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
    - name: Run pip install .
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test running installed package
      if: runner.os != 'Windows'
      run: picard --long-version --no-crash-dialog
    - name: Verify sdist package
      if: runner.os != 'Windows'
      run: |
        pip install pytest
        scripts/package/run-sdist-test.sh
